sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456chy
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGjd6mXgWvbS2TKFBub
    access-key-secret: a2WzxiDVRWikwkJ99vSBljPHXMsMHI
    bucket-name: skytake-chy
  redis:
      host: localhost
      port: 6379
      database: 1
  wechat:
    appid: wx7cad647a6ed546fa
    secret: 2304c8e5decf69c859aa01aac770d723
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    #weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://79b938f9.r33.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://79b938f9.r33.cpolar.top/notify/refundSuccess
  shop:
    address: 重庆市巴南区南泉街道白鹤村16号重庆工程学院(南泉校区)
  baidu:
    ak: rE4twI6f30osWy4PSfTDLs5gmB2a7iF7